# Generated by Django 5.2.6 on 2025-10-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0008_remove_customermonthlycommission_commission_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='whatsapp_url',
        ),
    ]
