# Generated by Django 5.2.6 on 2025-10-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0010_deliveryagent_deliveryassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='delivery_agent',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='order',
        ),
        migrations.DeleteModel(
            name='DeliveryAgent',
        ),
        migrations.DeleteModel(
            name='DeliveryAssignment',
        ),
    ]
