# Generated by Django 5.2.6 on 2025-10-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0014_alter_bill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_paid_balance',
        ),
    ]
