# Generated by Django 5.2.6 on 2025-11-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0018_cashbookentry_coin1_cashbookentry_coin10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='frozen',
            field=models.BooleanField(default=False, help_text='If true, item is frozen and not displayed in app except items dashboard'),
        ),
    ]
