# Generated by Django 5.2.6 on 2025-11-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0019_item_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='commission_deducted',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission amount deducted from this bill', max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='commission_month',
            field=models.IntegerField(blank=True, help_text='Month for which commission was deducted', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='commission_year',
            field=models.IntegerField(blank=True, help_text='Year for which commission was deducted', null=True),
        ),
        migrations.AddField(
            model_name='customermonthlycommission',
            name='status',
            field=models.BooleanField(default=False, help_text='Whether the commission has been deducted from a bill'),
        ),
        migrations.DeleteModel(
            name='CustomerMonthlyPurchase',
        ),
    ]
