# Generated by Django 5.2.6 on 2025-11-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0020_bill_commission_deducted_bill_commission_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_commissioned',
            field=models.BooleanField(default=False, help_text='Whether this customer is eligible for commission calculation'),
        ),
    ]
