# Generated by Django 5.2.6 on 2025-11-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0022_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='company',
            new_name='company_old',
        ),
    ]
