# Generated by Django 5.2.6 on 2025-11-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0024_item_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='company_old',
        ),
    ]
