# Generated by Django 5.2.6 on 2025-11-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0025_remove_item_company_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypayment',
            name='company_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_payments', to='milk_agency.company'),
        ),
    ]
