# Generated by Django 5.2.6 on 2025-11-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0026_dailypayment_company_new'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailypayment',
            unique_together={('company_new', 'date')},
        ),
        migrations.RemoveField(
            model_name='dailypayment',
            name='company',
        ),
    ]
