# Generated by Django 5.2.6 on 2025-11-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0027_alter_dailypayment_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailypayment',
            old_name='company_new',
            new_name='company',
        ),
        migrations.AlterUniqueTogether(
            name='dailypayment',
            unique_together={('company', 'date')},
        ),
    ]
