# Generated by Django 5.2.6 on 2025-11-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0028_rename_company_new_dailypayment_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
