# Generated by Django 5.2.6 on 2025-12-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0030_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_delivery',
            field=models.BooleanField(default=False, help_text='Whether this customer is eligible for delivery'),
        ),
    ]
