# Generated by Django 5.2.6 on 2026-02-17 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0033_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbalance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='milk_agency.bill'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fuel', 'Fuel'), ('Rent', 'Rent'), ('Electricity', 'Electricity'), ('Repairs', 'Repairs'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['invoice_date'], name='milk_agency_invoice_9d5524_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['customer'], name='milk_agency_custome_c1d9c0_idx'),
        ),
    ]
