# Generated by Django 5.2.6 on 2026-02-20 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0034_bankbalance_date_bill_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypaymentsummary',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_summaries', to='milk_agency.company'),
        ),
    ]
