# Generated by Django 5.2.6 on 2026-02-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0035_monthlypaymentsummary_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankbalance',
            name='date',
        ),
        migrations.AddField(
            model_name='dailypayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
