# Generated by Django 5.2.6 on 2026-02-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0036_remove_bankbalance_date_dailypayment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('user', 'User'), ('delivery', 'Delivery')], default='retailer', max_length=20),
        ),
    ]
