# Generated by Django 5.2.6 on 2026-03-06 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0038_subscriptionplan_subscriptionitem_userpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_in_days',
            field=models.IntegerField(default=1, help_text='Duration of the subscription in days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the subscription plan is active'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, help_text='Details about the subscription plan', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Name of the subscription plan', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the subscription plan', max_digits=10),
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Start date of the subscription')),
                ('end_date', models.DateField(help_text='End date of the subscription')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is currently active')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='milk_agency.subscriptionplan')),
            ],
        ),
        migrations.AddField(
            model_name='userpayment',
            name='subscription',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='milk_agency.customersubscription'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_agency.item')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_agency.customersubscription')),
            ],
            options={
                'unique_together': {('subscription', 'item', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_agency.customersubscription')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
