# Generated by Django 5.2.6 on 2026-03-14 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0039_remove_userpayment_subscription_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('offer_for', models.CharField(choices=[('retailer', 'Retailer'), ('user', 'User')], max_length=20)),
                ('offer_type', models.CharField(help_text="Type of offer (e.g., 'Buy 1 Get 1', '20% Off')", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_qty', models.IntegerField(default=0)),
                ('offer_qty', models.IntegerField(default=0)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_agency.item')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_agency.offers')),
            ],
        ),
    ]
