# Generated by Django 5.2.6 on 2026-03-15 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0040_offers_offeritems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionpause',
            options={'ordering': ['-pause_date']},
        ),
        migrations.RemoveField(
            model_name='subscriptionpause',
            name='date',
        ),
        migrations.AddField(
            model_name='subscriptionpause',
            name='is_resumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionpause',
            name='pause_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='subscriptionpause',
            name='resume_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpause',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='milk_agency.customersubscription'),
        ),
        migrations.CreateModel(
            name='AutoUPISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=False)),
                ('last_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_upi_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
