# Generated by Django 5.2.6 on 2026-03-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0041_alter_subscriptionpause_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price of this item within the subscription', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated price of the subscription plan', max_digits=10),
        ),
    ]
