# Generated by Django 5.2.6 on 2026-03-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0042_subscriptionitem_price_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='per',
            field=models.CharField(choices=[('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month')], default='day', help_text='Billing period for this item price', max_length=10),
        ),
    ]
