# Generated by Codex on 2026-03-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_portal", "0010_fix_delivery_date_column"),
        ("milk_agency", "0043_subscriptionitem_per"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("failed", "Failed")], default="pending", max_length=20)),
                ("eta", models.DateTimeField(blank=True, help_text="Estimated delivery time", null=True)),
                ("delivered_at", models.DateTimeField(blank=True, help_text="Actual delivery time", null=True)),
                ("delivered_amount", models.DecimalField(decimal_places=2, default="0.00", help_text="Collected amount on delivery (if COD/UPI)", max_digits=12)),
                ("notes", models.TextField(blank=True, help_text="Delivery notes / failure reason")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivered_by", models.ForeignKey(blank=True, help_text="Staff user who delivered", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_deliveries", to=settings.AUTH_USER_MODEL)),
                ("order", models.OneToOneField(help_text="Linked customer order", on_delete=django.db.models.deletion.CASCADE, related_name="delivery_tracking", to="customer_portal.customerorder")),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["status"], name="milk_agency_status_fb2a7d_idx"),
                    models.Index(fields=["eta"], name="milk_agency_eta_4ce262_idx"),
                    models.Index(fields=["delivered_at"], name="milk_agency_deliver_77b472_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("skipped", "Skipped"), ("failed", "Failed")], default="pending", max_length=20)),
                ("eta", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivered_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscription_deliveries", to=settings.AUTH_USER_MODEL)),
                ("subscription_order", models.OneToOneField(help_text="Linked subscription order (one per day/item)", on_delete=django.db.models.deletion.CASCADE, related_name="delivery_tracking", to="milk_agency.subscriptionorder")),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["status"], name="milk_agency_status_3d0890_idx"),
                    models.Index(fields=["eta"], name="milk_agency_eta_2a42fd_idx"),
                    models.Index(fields=["delivered_at"], name="milk_agency_deliver_53d76e_idx"),
                ],
            },
        ),
    ]
