# Generated by Django 5.2.6 on 2026-03-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0043_subscriptionitem_per'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoUPISetting',
        ),
    ]
