# Generated by Django 5.2.6 on 2026-03-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0044_delete_autoupisetting'),
        ('milk_agency', '0044_orderdelivery_subscriptiondelivery'),
    ]

    operations = [
    ]
