# Generated by Django 5.2.6 on 2026-03-19 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0045_merge_20260320_0001'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderdelivery',
            new_name='milk_agency_status_ec77e6_idx',
            old_name='milk_agency_status_fb2a7d_idx',
        ),
        migrations.RenameIndex(
            model_name='orderdelivery',
            new_name='milk_agency_eta_b0aec9_idx',
            old_name='milk_agency_eta_4ce262_idx',
        ),
        migrations.RenameIndex(
            model_name='orderdelivery',
            new_name='milk_agency_deliver_64b2f7_idx',
            old_name='milk_agency_deliver_77b472_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptiondelivery',
            new_name='milk_agency_status_e8100b_idx',
            old_name='milk_agency_status_3d0890_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptiondelivery',
            new_name='milk_agency_eta_59c024_idx',
            old_name='milk_agency_eta_2a42fd_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptiondelivery',
            new_name='milk_agency_deliver_42fc90_idx',
            old_name='milk_agency_deliver_53d76e_idx',
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivered_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Collected amount on delivery (if COD/UPI)', max_digits=12),
        ),
    ]
