# Generated by Django 5.2.6 on 2026-03-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0046_rename_milk_agency_status_fb2a7d_idx_milk_agency_status_ec77e6_idx_and_more'),
        ('milk_agency', '0047_contact_customer'),
    ]

    operations = [
    ]
