# Generated by Django 5.2.6 on 2026-04-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0050_item_price_precision'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockinentry',
            new_name='milk_agency_date_5a35fb_idx',
            old_name='milk_agency_date_2fca4d_idx',
        ),
        migrations.RenameIndex(
            model_name='stockinentry',
            new_name='milk_agency_company_aad590_idx',
            old_name='milk_agency_company_ee3748_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fuel', 'Fuel'), ('Food', 'Food'), ('Rent', 'Rent'), ('Salary', 'Salary'), ('Electricity', 'Electricity'), ('Repair', 'Repair'), ('Others', 'Others')], max_length=20),
        ),
    ]
