# Generated by Django 5.2.6 on 2026-04-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0052_leakageentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leakageentry',
            new_name='milk_agency_date_10a8b6_idx',
            old_name='milk_agency_leakage_date_idx',
        ),
        migrations.RenameIndex(
            model_name='leakageentry',
            new_name='milk_agency_item_id_5ba2d6_idx',
            old_name='milk_agency_leakage_item_idx',
        ),
    ]
