# Generated by Django 5.2.6 on 2026-04-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0054_pushdevice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='milk_agency_custome_17f43d_idx',
            old_name='milk_agency_customer_7b3f55_idx',
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='milk_agency_last_se_fa2588_idx',
            old_name='milk_agency_last_se_7b4cfd_idx',
        ),
    ]
