# Generated by Django 5.2.6 on 2026-04-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0055_pushdevice_android_fields'),
        ('milk_agency', '0055_rename_milk_agency_customer_7b3f55_idx_milk_agency_custome_17f43d_idx_and_more'),
    ]

    operations = [
    ]
