# Generated by Django 5.2.6 on 2026-04-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0056_merge_20260409_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='callback_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='gateway',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='payment_order_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('gateway', 'Gateway')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20),
        ),
    ]
