# Generated by Django 5.2.6 on 2026-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0058_userpayment_gateway_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('EXPENCES', 'Expences')], default='CASH', max_length=20),
        ),
    ]
