# Generated by Django 5.2.6 on 2025-10-29 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_store', '0005_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Kasi Agency', 'Kasi Agency'), ('HUL', 'HUL'), ('ITC', 'ITC'), ('Best Price', 'Best Price'), ('Jio Mart', 'Jio Mart'), ('Coco Cola', 'Coco Cola'), ('Campa', 'Campa'), ('Cigarettes', 'Cigarettes'), ('Petrol', 'Petrol'), ('Others', 'Others')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
