# Generated by Django 5.2.6 on 2025-09-24 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c500', models.IntegerField(default=0)),
                ('c200', models.IntegerField(default=0)),
                ('c100', models.IntegerField(default=0)),
                ('c50', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop_name', models.CharField(blank=True, help_text="Name of the customer's shop", max_length=255)),
                ('retailer_id', models.CharField(blank=True, help_text='Unique identifier for the retailer', max_length=100)),
                ('flat_number', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('due', models.DecimalField(decimal_places=2, default=0, help_text="Customer's current balance (positive for due, negative for credit)", max_digits=12)),
                ('last_paid_balance', models.DecimalField(decimal_places=2, default=0, help_text='Last paid amount', max_digits=12)),
                ('milk_commission', models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage for milk products', max_digits=12)),
                ('curd_commission', models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage for curd products', max_digits=12)),
                ('frozen', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('password', models.CharField(blank=True, help_text="Customer's password for login", max_length=128, null=True)),
            ],
            options={
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('petrol', 'Petrol'), ('food', 'Food'), ('others', 'Others')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Unique item code', max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, help_text='Maximum Retail Price', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('pcs_count', models.IntegerField(default=0, help_text='Number of pieces per unit')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items_saved/')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('op_due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_paid', models.DecimalField(decimal_places=2, default=0, help_text='Last paid amount for this bill', max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, help_text='Total profit from this bill', max_digits=12)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('whatsapp_url', models.URLField(blank=True, help_text='Generated WhatsApp share URL for this bill', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='milk_agency.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('txn_id', models.CharField(blank=True, help_text='Transaction ID for the payment', max_length=100, null=True)),
            ],
            options={
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('retailer_id', models.CharField(help_text='Unique identifier for the retailer', max_length=100)),
                ('retailer_name', models.CharField(blank=True, help_text='Name of the retailer', max_length=255)),
                ('item_names', models.TextField(blank=True, help_text='Comma-separated list of all items sold')),
                ('item_quantities', models.TextField(blank=True, help_text='Comma-separated quantities for each item')),
                ('item_prices', models.TextField(blank=True, help_text='Comma-separated prices for each item')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'retailer_id'],
                'unique_together': {('date', 'retailer_id')},
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='milk_agency.bill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_agency.item')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_invoice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CustomerMonthlyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('milk_volume', models.DecimalField(decimal_places=2, default=0, help_text='Total volume of milk purchased', max_digits=12)),
                ('curd_volume', models.DecimalField(decimal_places=2, default=0, help_text='Total volume of curd purchased', max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_purchases', to='milk_agency.customer')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('customer', 'year', 'month')},
            },
        ),
    ]
