# Generated by Django 5.2.6 on 2025-09-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0002_alter_customer_options_customer_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='curd_commission',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='milk_commission',
        ),
    ]
