# Generated by Django 5.2.6 on 2025-10-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0004_bill_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySalesSummary',
        ),
    ]
