# Generated by Django 5.2.6 on 2025-10-19 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0005_delete_dailysalessummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('retailer_id', models.CharField(help_text='Unique identifier for the retailer', max_length=100)),
                ('retailer_name', models.CharField(blank=True, help_text='Name of the retailer', max_length=255)),
                ('item_names', models.TextField(blank=True, help_text='Comma-separated list of all items sold')),
                ('item_quantities', models.TextField(blank=True, help_text='Comma-separated quantities for each item')),
                ('item_prices', models.TextField(blank=True, help_text='Comma-separated prices for each item')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'retailer_id'],
                'unique_together': {('date', 'retailer_id')},
            },
        ),
    ]
