# Generated by Django 5.2.6 on 2025-10-19 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0006_dailysalessummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMonthlyCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('milk_volume', models.DecimalField(decimal_places=2, default=0, help_text='Average daily milk volume', max_digits=12)),
                ('curd_volume', models.DecimalField(decimal_places=2, default=0, help_text='Average daily curd volume', max_digits=12)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, help_text='Average daily total volume', max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission rate per liter', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total commission amount for the month', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('customer', 'year', 'month')},
            },
        ),
    ]
