# Generated by Django 5.2.6 on 2025-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0007_customermonthlycommission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermonthlycommission',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='customermonthlycommission',
            name='curd_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate for curd per liter', max_digits=10),
        ),
        migrations.AddField(
            model_name='customermonthlycommission',
            name='milk_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate for milk per liter', max_digits=10),
        ),
    ]
