# Generated by Django 5.2.6 on 2025-10-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customer_portal', '0004_initial'),
        ('milk_agency', '0009_remove_bill_pdf_file_remove_bill_whatsapp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(help_text='Phone number for login', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_type', models.CharField(blank=True, help_text='Type of vehicle (bike, scooter, van, etc.)', max_length=100)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number', max_length=50)),
                ('license_number', models.CharField(blank=True, help_text='Driving license number', max_length=50)),
                ('area', models.CharField(blank=True, help_text='Primary delivery area', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='milk_agency_delivery_agent_groups', related_query_name='milk_agency_delivery_agent', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='milk_agency_delivery_agent_permissions', related_query_name='milk_agency_delivery_agent', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('can_deliver_orders', 'Can deliver orders'), ('can_generate_bills', 'Can generate bills at delivery')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('returned', 'Returned')], default='assigned', max_length=20)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, help_text='Notes from delivery agent')),
                ('customer_feedback', models.TextField(blank=True, help_text='Feedback from customer')),
                ('bill_generated', models.BooleanField(default=False, help_text='Whether bill was generated at delivery')),
                ('delivery_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_agency_assignments', to='milk_agency.deliveryagent')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milk_agency_delivery_assignment', to='customer_portal.customerorder')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
