# Generated by Django 5.2.6 on 2025-10-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('milk_agency', '0011_remove_deliveryassignment_delivery_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this customer belongs to.', related_name='customer_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this customer.', related_name='customer_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(help_text='Phone number for login', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, help_text='Delivery area', max_length=255)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this delivery agent belongs to.', related_name='delivery_agent_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this delivery agent.', related_name='delivery_agent_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
