# Generated by Django 5.2.6 on 2025-10-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0012_alter_customer_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAgent',
        ),
    ]
