# Generated by Django 5.2.6 on 2025-11-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0015_remove_customer_last_paid_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailypayment',
            name='txn_id',
        ),
    ]
