# Generated by Django 5.2.6 on 2025-11-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0016_remove_dailypayment_txn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='c10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='c20',
            field=models.IntegerField(default=0),
        ),
    ]
