# Generated by Django 5.2.6 on 2025-11-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_agency', '0017_cashbookentry_c10_cashbookentry_c20'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='coin1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='coin10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='coin2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='coin20',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='coin5',
            field=models.IntegerField(default=0),
        ),
    ]
