# Generated by Django 5.2.6 on 2025-09-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0002_delete_customerorderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
