# Generated by Django 5.2.6 on 2025-09-24 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milk_agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order number', max_length=50, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(blank=True, help_text='Requested delivery date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes and feedback')),
                ('delivery_address', models.TextField(help_text='Delivery address')),
                ('phone', models.CharField(blank=True, help_text='Contact phone for delivery', max_length=20)),
                ('additional_notes', models.TextField(blank=True, help_text="Customer's additional notes")),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total order amount', max_digits=12)),
                ('approved_total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Admin approved total amount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='milk_agency.customer')),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(help_text='Quantity requested by customer')),
                ('requested_price', models.DecimalField(decimal_places=2, help_text='Price per unit requested', max_digits=10)),
                ('approved_quantity', models.IntegerField(default=0, help_text='Quantity approved by admin')),
                ('approved_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit approved by admin', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount per unit', max_digits=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for this item')),
                ('requested_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_agency.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_portal.customerorder')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
