# Generated by Django 5.2.6 on 2025-11-23 18:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderitem',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
