# Generated by Django 5.2.6 on 2025-11-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0005_customerorderitem_discount_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
