# Generated by Django 5.2.6 on 2026-03-13 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_remove_customerorder_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
    ]
