# Generated by Django 5.2.6 on 2026-03-13 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0007_alter_customerorder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
