# Generated by Django 5.2.6 on 2026-03-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0008_alter_customerorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Charge for Delivery', max_digits=12),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivery_date',
            field=models.DateField(db_column='delivery_date', default='2026-03-18', help_text='Expected delivery date'),
            preserve_default=False,
        ),
    ]
