# Generated by Django 5.2.6 on 2026-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0010_fix_delivery_date_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='delivery_date',
            field=models.DateField(help_text='Expected delivery date'),
        ),
    ]
