# Generated by Django 5.2.6 on 2026-04-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0014_customerorder_gateway_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerGatewayPayment',
        ),
    ]
