# Generated by Django 5.2.6 on 2025-10-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_store', '0004_bankbalance_cashbookentry_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Kasi Agency', 'Kasi Agency'), ('HUL', 'HUL'), ('ITC', 'ITC'), ('Best Price', 'Best Price'), ('Jio Mart', 'Jio Mart'), ('Coco Cola', 'Coco Cola'), ('Campa', 'Campa'), ('Cigarettes', 'Cigarettes'), ('Others', 'Others')], max_length=20),
        ),
    ]
