# Generated by Django 5.2.6 on 2025-11-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_store', '0008_cashbookentry_c10_cashbookentry_c20'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
