"""
Django settings for SVD project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import json
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

PAYTM_MID = os.environ.get("PAYTM_MID", "Resell00448005757124")
PAYTM_MERCHANT_KEY = os.environ.get("PAYTM_MERCHANT_KEY", "KXHUJH8Ywq9pUkkr")
PAYTM_WEBSITE = os.environ.get("PAYTM_WEBSITE", "WEBSTAGING")
PAYTM_ENV = os.environ.get("PAYTM_ENV", "staging")
PAYTM_BASE_URL = os.environ.get(
    "PAYTM_BASE_URL",
    "https://securegw-stage.paytm.in"
    if PAYTM_WEBSITE.upper() == "WEBSTAGING" or PAYTM_ENV.lower() == "staging"
    else "https://securegw.paytm.in",
)

PAYTM_INDUSTRY_TYPE_ID = os.environ.get("PAYTM_INDUSTRY_TYPE_ID", "Retail")
PAYTM_CHANNEL_ID = os.environ.get("PAYTM_CHANNEL_ID", "WEB")
PAYTM_CHANNEL_ID_MOBILE = os.environ.get("PAYTM_CHANNEL_ID_MOBILE", "WAP")

PAYTM_CALLBACK_URL = os.environ.get(
    "PAYTM_CALLBACK_URL",
    "https://svdagencies.shop/milk_agency/users/orders/paytm/callback/",
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-qt%cg=y7$8hoo%4#2ss9sl0l2b+%)tt!wg7e$6@+j%owo@li##',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'svdagencies.shop',
    'www.svdagencies.shop',
    'svd-dqw3.onrender.com',
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [
    "https://svdagencies.shop",
    "https://www.svdagencies.shop",
    "https://svd-dqw3.onrender.com",
    "https://*.paytm.in",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'general_store',
    'milk_agency',
    'customer_portal',
    'mathfilters',
    'rest_framework',
    'rest_framework.authtoken',
    'api',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 🚀 Add this line (your actual middleware)
    'SVD.middleware.NoCacheMiddleware.NoCacheMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'SVD.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'SVD.context_processors.firebase_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'SVD.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#SQLITE_PATH = BASE_DIR / 'db.sqlite3'

'''USE_MYSQL = os.environ.get('USE_MYSQL', '').lower() in {'1', 'true', 'yes'}

if USE_MYSQL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('MYSQL_DATABASE', 'svd_db'),
            'USER': os.environ.get('MYSQL_USER', 'svd_user'),
            'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'StrongPassword123!'),
            'HOST': os.environ.get('MYSQL_HOST', 'localhost'),
            'PORT': os.environ.get('MYSQL_PORT', '3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': SQLITE_PATH,
        }
    }

DATABASES['backup'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': SQLITE_PATH,
} '''

DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#Auth User Model
AUTH_USER_MODEL = 'milk_agency.Customer'


# Use Django's default authentication backend
AUTHENTICATION_BACKENDS = [
    'customer_portal.authentication.CustomerBackend',  # Customers first
    'django.contrib.auth.backends.ModelBackend',       # Admins second
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
#STATIC_ROOT = BASE_DIR / 'staticfiles_build'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploaded files)
MEDIA_URL = '/images/'
MEDIA_ROOT = BASE_DIR / 'images'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL for authentication redirects
# https://docs.djangoproject.com/en/5.2/ref/settings/#login-url
LOGIN_URL = '/customer/login/'


# Firebase web + push configuration
FIREBASE_WEB_CONFIG = {
    "apiKey": os.environ.get("FIREBASE_API_KEY", "AIzaSyBrnyg2eZowgA9uv7vjMhMCvId2XgskrVs"),
    "authDomain": os.environ.get(
        "FIREBASE_AUTH_DOMAIN",
        "sri-vijaya-durga-agencie-16255.firebaseapp.com",
    ),
    "projectId": os.environ.get("FIREBASE_PROJECT_ID", "sri-vijaya-durga-agencie-16255"),
    "storageBucket": os.environ.get(
        "FIREBASE_STORAGE_BUCKET",
        "sri-vijaya-durga-agencie-16255.firebasestorage.app",
    ),
    "messagingSenderId": os.environ.get("FIREBASE_MESSAGING_SENDER_ID", "910196896431"),
    "appId": os.environ.get("FIREBASE_APP_ID", "1:910196896431:web:5747bfbf37af910ad59a5a"),
    "measurementId": os.environ.get("FIREBASE_MEASUREMENT_ID", "G-TR3FLXCYH4"),
}
FIREBASE_WEB_VAPID_KEY = os.environ.get(
    "FIREBASE_WEB_VAPID_KEY",
    "BOTwWU5cSbYJMKUm5Hq51YnI7hRO8TcSUb9mYYrJi-QEf-yhDsQNqlDmY2zogXEKx3IxfLxwrrJ0nvGY77ATwM",
)
FIREBASE_SERVICE_ACCOUNT_PATH = os.environ.get("FIREBASE_SERVICE_ACCOUNT_PATH", "").strip()
FIREBASE_SERVICE_ACCOUNT_JSON = os.environ.get("FIREBASE_SERVICE_ACCOUNT_JSON", "").strip()
FIREBASE_PUSH_ENABLED = bool(FIREBASE_WEB_CONFIG.get("messagingSenderId") and FIREBASE_WEB_VAPID_KEY)

if FIREBASE_SERVICE_ACCOUNT_JSON:
    try:
        FIREBASE_SERVICE_ACCOUNT_INFO = json.loads(FIREBASE_SERVICE_ACCOUNT_JSON)
    except json.JSONDecodeError:
        FIREBASE_SERVICE_ACCOUNT_INFO = None
else:
    FIREBASE_SERVICE_ACCOUNT_INFO = None
